USE Day2db;

SELECT * FROM EMPLOYEESS;
SELECT * FROM DEPARTMENT;
SELECT * FROM MANAGER;
SELECT * FROM PROJECT;
--SUBQUERIES --
--FIND THE EMPLOYEE WHOSE SALARY IS MORE THAN THE AVERAGE SALARY EARNED BY ALL EMPLOYEE--
--1.FIRST OF ALL FIND THE AVERAGE SALARY  AND 
--2.THEN FIND THE ALL THE EMPLOYEE WHO EARNED MORE THEN THE AVERAGE SALARY--

SELECT * FROM EMPLOYEESS--OUTER QUERY
WHERE SALARY >(SELECT AVG(SALARY) FROM EMPLOYEESS);--INNER QUERY




SELECT  UPPER(emp_name) 
FROM EMPLOYEESS;

select LOWER(emp_name) from EMPLOYEESS;

select REPLACE(emp_name,'rahul','rohan') from EMPLOYEESS;
SELECT TRIM(EMP_NAME) AS TR FROM EMPLOYEESS;


